### ISSUE TITLE
Compilation breaks when enabling OP-TEE benchmark.

### ISSUE THREAD

**Issue by ChrisG55** [linaro-swg/optee_benchmark#11]
Setup:
- Operating system: Ubuntu 18.04.1 LTS
- OP-TEE manifest.git: 3.3.0 using `qemu_v8.xml`
- GCC version: 8.2.1

How to reproduce:
-  Follow the instructions in [OP-TEE build.git](https://github.com/OP-TEE/build/blob/master/README.md) up to section 7.5 Build the solution.
-  Enable the `CFG_TEE_BENCHMARK` configuration variable and continue with section 7.5 Build the solution in OP-TEE build.git by running make from within the `build` directory. This will trigger at some point the build process in the `optee_benchmark` directory.
```
$ CFG_TEE_BENCHMARK=y make
```

Reproducibility: always

Relevant build output: 
```
-- Build files have been written to: /home/ubuntu/devel/optee/out-br/build/optee_benchmark-1.0
>>> optee_benchmark 1.0 Building
PATH="/home/ubuntu/devel/optee/out-br/host/bin:/home/ubuntu/devel/optee/out-br/host/sbin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"  /usr/bin/make -j9  -C /home/ubuntu/devel/optee/out-br/build/optee_benchmark-1.0/
Scanning dependencies of target benchmark
[ 33%] Building C object CMakeFiles/benchmark.dir/main.c.o
[ 66%] Building C object CMakeFiles/benchmark.dir/benchmark_aux.c.o
In file included from main.c:46:
main.c: In function ‘alloc_bench_buf’:
common.h:44:35: error: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘intptr_t’ {aka ‘long int’} [-Werror=format=]
 #define INFO(fmt, args...) printf("[" OUTPUT_APP_PREFIX \
                                   ^~~
main.c:109:2: note: in expansion of macro ‘INFO’
  INFO("ts buffer paddr = %x, size = %d\n", paddr_ts_buf, size);
  ^~~~
main.c:109:27: note: format string is defined here
  INFO("ts buffer paddr = %x, size = %d\n", paddr_ts_buf, size);
                          ~^
                          %lx
In file included from main.c:46:
common.h:44:35: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
 #define INFO(fmt, args...) printf("[" OUTPUT_APP_PREFIX \
                                   ^~~
main.c:109:2: note: in expansion of macro ‘INFO’
  INFO("ts buffer paddr = %x, size = %d\n", paddr_ts_buf, size);
  ^~~~
main.c:109:38: note: format string is defined here
  INFO("ts buffer paddr = %x, size = %d\n", paddr_ts_buf, size);
                                     ~^
                                     %ld
cc1: all warnings being treated as errors
CMakeFiles/benchmark.dir/build.make:62: recipe for target 'CMakeFiles/benchmark.dir/main.c.o' failed
make[5]: *** [CMakeFiles/benchmark.dir/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/benchmark.dir/all' failed
make[4]: *** [CMakeFiles/benchmark.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
package/pkg-generic.mk:229: recipe for target '/home/ubuntu/devel/optee/out-br/build/optee_benchmark-1.0/.stamp_built' failed
make[2]: *** [/home/ubuntu/devel/optee/out-br/build/optee_benchmark-1.0/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/ubuntu/devel/optee/out-br'
common.mk:201: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
```

The `-Werror` flag was added in commit 97f12d21cfa681aa3a0c30cfa2f7f12459195784.
55fcc4ae0de4b9a2f7253562f8083694e69a8e33 introduces new variables that are used as arguments in call to `INFO` macro. In principle these compile time errors should have been raised since 55fcc4ae0de4b9a2f7253562f8083694e69a8e33.
Pull request [#12](https://github.com/linaro-swg/optee_benchmark/pull/12) has been submitted to fix the issue.

**Comment by ChrisG55** [comment]
While commit ecba70dd88f33f3c770a4c564b49d7e872eab34e fixes the build errors, the manifests in [manifest.git branch 3.3.0](https://github.com/OP-TEE/manifest/tree/3.3.0) still refer to the previous commit 845a783563f29c3915797cab0faa2a3d7eeb62ef. It becomes a bit combersome, if `main.c` has to be patched "manually" before continuing with the build process while relying on the stable 3.3.0 branch. An easy solution would be to move the `tag: 3.3.0` from commit 845a783563f29c3915797cab0faa2a3d7eeb62ef to commit ecba70dd88f33f3c770a4c564b49d7e872eab34e. Another solution would be to patch the manifests `default.xml`, `qemu_v8.xml` and `rpi3.xml` in  [manifest.git branch 3.3.0](https://github.com/OP-TEE/manifest/tree/3.3.0) to point to commit ecba70dd88f33f3c770a4c564b49d7e872eab34e. Would it be possible to move `tag: 3.3.0` to commit ecba70dd88f33f3c770a4c564b49d7e872eab34e?

**Comment by jockebech** [comment]
@ChrisG55 , no we don't move any stable tags, since that would make them not stable any more and would jeopardize our releases. Fixes, like yours here will end up in the next release (3.4.0 is targeted to Jan 25th 2019). If people need things sooner than that, then they have two options 1) Run latest manifest instead of a stable 2) Cherry pick the patches.

**Comment by ChrisG55** [comment]
Hi @jbech-linaro, thank you for your answer. I will use the lastest manifest then.
