### ISSUE TITLE
can't compile optee_benchmark using  make CFG_TEE_BENCHMARK=y

### ISSUE THREAD

**Issue by liwei3013** [linaro-swg/optee_benchmark#17]
make[1]: Leaving directory '/home/liwei/optee/linux'
>>> optee_benchmark_ext 1.0 Syncing from source dir
make -C /home/liwei/optee/build/../linux LOCALVERSION= CROSS_COMPILE=" /home/liwei/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" ARCH=arm64 Image scripts_gdb
make[1]: Entering directory '/home/liwei/optee/linux'
ERROR:  does not exist
package/pkg-generic.mk:186: recipe for target '/home/liwei/optee/out-br/build/optee_benchmark_ext-1.0/.stamp_rsynced' failed
make[2]: *** [/home/liwei/optee/out-br/build/optee_benchmark_ext-1.0/.stamp_rsynced] Error 1
#Makefile:23: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/liwei/optee/out-br'
common.mk:289: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
make: *** Waiting for unfinished jobs....
#####

**Comment by Sadiq1811** [comment]
@jbech-linaro i was able to solve this via https://github.com/OP-TEE/build/pull/553
Please have a look

**Comment by Sadiq1811** [comment]
@jbech-linaro could we please close this issue ?

**Comment by jockebech** [comment]
> @jbech-linaro could we please close this issue ?

Absolutely, again thanks!
